### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ch31z3r83** [mercadopago/devsite-docs#1118]
On the document type capture, what is the suggestion if I have a website where most of the clients are foreigners and they are not used to fill out document number while making payments neither they would have a document standard that meets the requirements of a CPF if I am a merchant based in Brazil? What should I do in this case? How to bypass or omit the document type field during checkout?

Thank you,

Cheizer

**Comment by MercadoPagoDevelopers** [comment]
Hi,

In order to help you with your question, please contact us through our [support channel](https://www.mercadopago.com.br/developers/pt/support/contact) so that we can answer you as soon as possible.

If possible, inform which product / payment method you are integrating. CPF is not a mandatory field for card payments at checkout api for example

Graciously,

** Mercado Pago developer team **
