### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by denisson** [mercadopago/devsite-docs#790]
I am trying to find more information about plans and subscriptions, but I couldn't find anything here about it.

Are https://api.mercadopago.com/v1/plans and https://api.mercadopago.com/v1/subscriptions working?

Thank you in advance

**Comment by andreszs** [comment]
Welcome to the Mercadopago docs discussion.

As far as I know, the subscription service has been **dropped**, probably due to ill-use by developers and/or user complaints.

It would be nice to have this option available on a pre-approval basis, because some services depend on a monthly subscription, such as newspapers access and other premium services. Unfortunately there are no direct channels to contact the staff about this, we are mostly left in the dark about the ideas and implementations from the developers team.

**Comment by denisson** [comment]
@andreszs Thank you for your reply! I think I will try to use another service, then.

**Comment by MercadoPagoDevelopers** [comment]
Hola, @denisson 

Para poder te ajudar com sua dúvida, por favor nos contate pelo nosso  [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/) para que possamos te responder o quanto antes.
Teremos novidades em relação a subscriptions mos próximos meses.

Atenciosamente,
Equipe de suporte a desenvolvedores de Mercado Pago
